name: hrgo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo_oil.png
    - assets/profile.jpg

