name: hrgo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.12

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.3
  intl: ^0.20.2
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.3
  share_plus: ^12.0.1
  webview_flutter: ^4.13.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/chat/chat.html
    - assets/logo_oil.png
    - assets/profile.jpg

